from __future__ import annotations


class SublimeText:
    globalKeys = [
        "foreground",
        "background",
        "invisibles",
        "gutter_foreground",
        "gutter",
        "caret",
        "block_caret",
        "selection",
        "selection_border",
        "inactive_selection",
        "selection_border_width",
        "selection_corner_style",
        "line_highlight",
        "highlight",
        "find_highlight",
        "find_highlight_foreground",
        "guide",
        "active_guide",
        "stack_guide",
        "misspelling",
        "fold_marker",
        "minimap_border",
        "accent",
        "brackets_options",
        "brackets_foreground",
        "bracket_contents_foreground",
        "bracket_contents_options",
        "tags_options",
        "tags_foreground",
        "line_diff_added",
        "line_diff_modified",
        "line_diff_deleted",
        "line_diff_width",
        "shadow",
        "shadow_width",
    ]
